
---
alerters:
  discord:
    webhook_url: https://discord.com/api/webhooks/https://discord.com/api/webhooks/826634417719738369/expHi98lSoyOhjl4mKxa9GIKxiRZEO-9S9erliMWjCjQ500gEXu_S7Gd9XsvnzcpkuF9
    mentions:
      - stambot3000
      - everyone
...
