
---
refresh_interval: 2 # seconds
max_price: 1500 # dollars
urls:
  - https://www.bestbuy.ca/en-ca/product/evga-geforce-rtx-3080-xc3-ultra-gaming-10gb-gddr6x-video-card/15084753
  - https://www.bestbuy.ca/en-ca/product/evga-geforce-rtx-3080-xc3-ultra-gaming-10gb-gddr6x-video-card/15084753
  - https://www.bestbuy.ca/en-ca/product/asus-tuf-gaming-nvidia-geforce-rtx-3080-10gb-gddr6x-video-card/14953248
  - https://www.bestbuy.ca/en-ca/product/asus-rog-strix-nvidia-geforce-rtx-3080-10gb-gddr6x-video-card/14954116
  - https://www.bestbuy.ca/en-ca/product/msi-nvidia-geforce-rtx-3080-ventus-3x-10gb-gddr6x-video-card/14950588
  - https://www.bestbuy.ca/en-ca/product/zotac-nvidia-geforce-rtx-3080-trinity-10gb-gddr6x-video-card/14953249
  - https://www.bestbuy.ca/en-ca/product/zotac-nvidia-geforce-rtx-3080-trinity-oc-10gb-gddr6x-video-card/15000077
  - https://www.bestbuy.ca/en-ca/product/nvidia-geforce-rtx-3070-8gb-gddr6-video-card-only-at-best-buy/15078017
  - https://www.bestbuy.ca/en-ca/product/asus-tuf-gaming-nvidia-geforce-rtx-3070-2x-oc-8gb-gddr6-video-card/15053087
  - https://www.bestbuy.ca/en-ca/product/evga-geforce-rtx-3070-xc3-ultra-8gb-gddr6-video-card/15147122
  - https://www.bestbuy.ca/en-ca/product/msi-nvidia-geforce-rtx-3070-ventus-3x-oc-8gb-gddr6-video-card/15038016
  - https://www.bestbuy.ca/en-ca/product/zotac-nvidia-geforce-rtx-3070-twin-edge-8gb-gddr6x-video-card/15000079
  - https://www.bestbuy.ca/en-ca/product/zotac-nvidia-geforce-rtx-3070-twin-edge-oc-8gb-gddr6x-video-card/15000078
  - https://www.bestbuy.ca/en-ca/product/asus-dual-nvidia-geforce-rtx-3070-2x-oc-8gb-gddr6-video-card/15053086
  - https://www.bestbuy.ca/en-ca/product/asus-rog-strix-nvidia-geforce-rtx-3070-oc-8gb-gddr6-video-card/15053085
  - https://www.bestbuy.ca/en-ca/product/zotac-nvidia-geforce-rtx-3070-amp-holo-8gb-gddr6-video-card/15268899
  - https://www.bestbuy.ca/en-ca/product/nvidia-geforce-rtx-3060-ti-8gb-gddr6-video-card/15166285
  - https://www.bestbuy.ca/en-ca/product/evga-nvidia-geforce-rtx-3060-ti-ftw3-ultra-8gb-gddr6-video-card/15229237
  - https://www.bestbuy.ca/en-ca/product/msi-nvidia-geforce-rtx-3060-ti-ventus-2x-oc-8gb-gddr6-video-card/15178453
  - https://www.amd.com/en/direct-buy/5458373400/ca
  - https://www.amd.com/en/direct-buy/5496921500/ca
  - https://www.amd.com/en/direct-buy/5458372800/ca
  - https://www.amd.com/en/direct-buy/5496921400/ca
  - https://www.bhphotovideo.com/c/product/1593650-REG/asus_tuf_rtx3080_o10g_gaming_tuf_gaming_geforce_rtx.html?SID=s1618354315209p5tua52439
  - https://www.bhphotovideo.com/c/product/1609792-REG/xfx_force_rx_68xlatbd9_speedster_merc_319_amd.html
  - https://www.bhphotovideo.com/c/product/1609027-REG/asus_rog_strix_rx6800_o16g_gaming_rog_strix_radeon_rx.html
  - https://www.bhphotovideo.com/c/product/1620004-REG/msi_r6800xtgxt16_radeon_rx_6800_xt.html
  - https://www.bhphotovideo.com/c/product/1620003-REG/msi_r6800gxt16_radeon_rx_6800_gaming.html
  - https://www.bhphotovideo.com/c/product/1609028-REG/asus_tuf_rx6800_o16g_gaming_tuf_gaming_radeon_rx.html
  - https://www.bhphotovideo.com/c/product/1558731-REG/asus_tuf_3_rx5700xt_o8g_evo_gaming_tuf_gaming_x3_radeon.html
  - https://www.bhphotovideo.com/c/product/1506619-REG/msi_radeon_rx_5700_xt.html
  - https://www.memoryexpress.com/Products/MX00114997
  - https://www.memoryexpress.com/Products/MX00115186
  - https://www.memoryexpress.com/Products/MX00114937
  - https://www.memoryexpress.com/Products/MX00114938
  - https://www.memoryexpress.com/Products/MX00115123
  - https://www.memoryexpress.com/Products/MX00115751
  - https://www.memoryexpress.com/Products/MX00115049
  - https://www.memoryexpress.com/Products/MX00114996
  - https://www.memoryexpress.com/Products/MX00115124
  - https://www.memoryexpress.com/Products/MX00115187
  - https://www.memoryexpress.com/Products/MX00115289
  - https://www.myteknology.com/ShopItem.aspx?SessionCode=A2DFE207FFDA4CEA9F56117A6F1A8CA8&Toc=136337:0&CatCoNo=136337&ProductNo=13588373&ID=13588373
  - https://www.frontierpc.com/W000423244.html
  - https://www.frontierpc.com/W000423093.html
  - https://www.frontierpc.com/W000503201.html
  - https://store.ashlin.ca/ssproduct.asp?pf_id=-2067911433
  - https://store.ashlin.ca/ssproduct.asp?pf_id=-2068890914
  - https://store.ashlin.ca/ssproduct.asp?pf_id=-2067911431
  - https://store.ashlin.ca/ssproduct.asp?pf_id=-2068890915
  - https://www.pc-canada.com/item/GV%2DR68GAMING%20OC%2D16GD.html
  - https://www.pc-canada.com/item/ROG%2DSTRIX%2DRX6800%2DO16G%2DGAM.html
  - https://www.pc-canada.com/item/TUF%2DRX6800%2DO16G%2DGAMING.html
  - https://www.pcczone.com/gigabyte-radeon-rx6800-gaming-oc-16gb-gddr6-video-card-gv-r68gaming-oc-16gd.html
  - https://www.pcczone.com/sapphire-amd-radeon-rx6800-xt-16gb-gddr6-video-card-21304-01-20g.html
  - https://www.bhphotovideo.com/c/product/1609027-REG/asus_rog_strix_rx6800_o16g_gaming_rog_strix_radeon_rx.html
  - https://www.bhphotovideo.com/c/product/1609028-REG/asus_tuf_rx6800_o16g_gaming_tuf_gaming_radeon_rx.html
  - https://www.bhphotovideo.com/c/product/1620003-REG/msi_r6800gxt16_radeon_rx_6800_gaming.html
  - https://www.directdial.com/ca/item/gigabyte-aorus-nvidia-geforce-rtx-3080-graphic-card/gv-n3080aorus-x-10gd
  - https://www.directdial.com/ca/item/msi-amd-radeon-rx-6800-xt-graphic-card/r6800xtgxt16
  - https://www.directdial.com/ca/item/zotac-nvidia-geforce-rtx-3080-graphic-card/zt-a30800f-10p
  - https://www.directdial.com/ca/item/pny-nvidia-geforce-rtx-3080-graphic-card/vcg308010tfxppb
  - https://www.directdial.com/ca/item/asus-tuf-amd-radeon-rx-6800-xt-graphic-card/tuf-rx6800xt-o16g-gaming
  - https://www.directdial.com/ca/item/msi-amd-radeon-rx-6800-graphic-card/r6800gxt16
  - https://www.directdial.com/ca/item/evga-nvidia-geforce-rtx-3080-graphic-card/10g-p5-3897-kr
  - https://www.directdial.com/ca/item/zotac-nvidia-geforce-rtx-3080-graphic-card/zt-a30800j-10p
  - https://www.directdial.com/ca/item/gigabyte-geforce-rtx-3080-vision-video-graphics-card/gv-n3080vision-oc-10gd
  - https://www.directdial.com/ca/item/asus-tuf-amd-radeon-rx-6800-xt-graphic-card/tuf-rx6800xt-o16g-gaming
  - https://www.directdial.com/ca/item/msi-amd-radeon-rx-6800-graphic-card/r6800gxt16
  - https://www.directdial.com/ca/item/asus-tuf-amd-radeon-rx-6800-graphic-card/tuf-rx6800-o16g-gaming
  - https://www.memoryexpress.com/Products/MX00115188
  - https://www.memoryexpress.com/Products/MX00114940
  - https://www.memoryexpress.com/Products/MX00115048
  - https://www.memoryexpress.com/Products/MX00115741
  - https://www.memoryexpress.com/Products/MX00115474
  - https://www.memoryexpress.com/Products/MX00115288
  - https://www.shoprbc.com/ca/shop/product_details.php?pid=56118226
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_558&item_id=188911
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_558&item_id=187853
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_558&item_id=185891
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_558&item_id=185753
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_558&item_id=185461
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_558&item_id=188643
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_558&item_id=187854
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_558&item_id=185460
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_558&item_id=185755
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_558&item_id=187784
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_558&item_id=185459
  - https://www.directdial.com/ca/item/asus-tuf-amd-radeon-rx-6800-graphic-card/tuf-rx6800-o16g-gaming
  - https://www.directdial.com/ca/item/gigabyte-nvidia-geforce-rtx-3070-graphic-card/gv-n3070vision-oc-8gd
  - https://www.directdial.com/ca/item/msi-rtx-3070-suprim-x-8g-nvidia-graphics/g3070sx8
  - https://www.directdial.com/ca/item/pny-nvidia-geforce-rtx-3070-graphic-card/vcg30708tfxppb
  - https://www.directdial.com/ca/item/asus-nvidia-geforce-rtx-3070-graphic-card/rtx3070-8g-ekhttps://www.directdial.com/ca/item/evga-nvidia-geforce-rtx-3070-graphic-card/08g-p5-3767-kr
  - https://www.directdial.com/ca/item/evga-nvidia-geforce-rtx-3070-graphic-card/08g-p5-3767-kr
  - https://www.directdial.com/ca/item/msi-rtx-3070-gaming-x-trio-nvidia-graphic-card/g3070gxt
  - https://www.directdial.com/ca/item/zotac-nvidia-geforce-rtx-3070-graphic-card/zt-a30700j-10p
  - https://www.directdial.com/ca/item/gigabyte-nvidia-geforce-rtx-3070-graphic-card/gv-n3070eagle-oc-8gd
  - https://www.directdial.com/ca/item/evga-nvidia-geforce-rtx-3070-graphic-card/08g-p5-3755-kr
  - https://www.directdial.com/ca/item/evga-nvidia-geforce-rtx-3060-ti-graphic-card/08g-p5-3667-kr
  - https://www.myteknology.com/ShopItem.aspx?SessionCode=A2DFE207FFDA4CEA9F56117A6F1A8CA8&Toc=136337:0&CatCoNo=136337&ProductNo=13588372&ID=13588372
  - https://www.myteknology.com/ShopItem.aspx?SessionCode=A2DFE207FFDA4CEA9F56117A6F1A8CA8&Toc=136337:0&CatCoNo=136337&ProductNo=13588370&ID=13588370
  - https://www.pcczone.com/sapphire-amd-radeon-rx6800-16gb-gddr6-video-card-21305-01-20g.html
  - https://www.pcczone.com/sapphire-amd-radeon-rx6800-16gb-gddr6-video-card-21305-01-20g.html
  - https://www.memoryexpress.com/Products/MX00115122
  - https://www.pc-canada.com/item/G206SVPC.html
  - https://www.pcczone.com/gigabyte-radeon-rtx5700-xt-8gb-gddr6-video-card-gv-r57xtaorus-8gd.html
  - https://www.pcczone.com/asus-amd-radeon-rx5700xt-8gb-gddr6-video-card-dual-rx5700xt-o8g-evo.html
  - https://www.pcczone.com/asus-rog-strix-radeon-rx-5700xt-oc-8gb-gddr6-video-card-rog-strix-rx5700xt-o8g-gaming.html
  - https://www.pcczone.com/sapphire-nitro-rx-5700-xt-8g-gddr6-video-card-11293-03-40g.html
  - https://www.pcczone.com/sapphire-pulse-rx-5700xt-8g-gddr6-video-card-11293-01-20g.html
  - https://www.bhphotovideo.com/c/product/1558731-REG/asus_tuf_3_rx5700xt_o8g_evo_gaming_tuf_gaming_x3_radeon.html
  - https://www.bhphotovideo.com/c/product/1506619-REG/msi_radeon_rx_5700_xt.html
  - https://www.bhphotovideo.com/c/product/1593336-REG/gigabyte_gv_r57xtgaming_oc_8gd_rev2_0_radeon_rx_5700_xt.html
  - https://www.directdial.com/ca/item/msi-amd-radeon-rx-5700-xt-graphic-card/r5700xtgx
  - https://www.directdial.com/ca/item/gigabyte-aorus-amd-radeon-rx-5700-xt-graphic-card/gv-r57xtaorus-8gd
  - https://www.directdial.com/ca/item/msi-amd-radeon-rx-5700-xt-graphic-card/r5700xtmhc
  - https://www.directdial.com/ca/item/gigabyte-amd-radeon-rx-5700-xt-graphic-card/gv-r57xtgaming-oc-8gd
  - https://www.directdial.com/ca/item/gigabyte-amd-radeon-rx-5700-xt-graphic-card/gv-r57xtgaming-oc-8gd-r2
  - https://www.staples.ca/products/2976002-en-msi-radeon-rx-5700-xt-mech-overclocked-8-gb-gddr6-graphics-card
  - https://www.frontierpc.com/W000185066.html
  - https://www.frontierpc.com/W000235975.html
  - https://www.softwarecity.ca/item/R5700XTMHC.html
  - https://www.softwarecity.ca/item/GV%2DR57XTGAMING%20OC%2D8GD%20R2.html
  - https://www.softwarecity.ca/item/GV%2DR57XTGAMING%20OC%2D8GD.html
  - https://www.softwarecity.ca/item/R5700XTGX.html
  - https://www.softwarecity.ca/item/GV%2DR57XTAORUS%2D8GD.html
  - https://www.softwarecity.ca/item/11265%2D05%2D20G.html
  - https://www.softwarecity.ca/item/GV%2DRX580GAMING%2D4GD.html
  - https://www.softwarecity.ca/item/GV%2DRX580AORUS%2D8GD.html
  - https://www.frontierpc.com/W000379203.html
  - https://www.frontierpc.com/W000403249.html
  - https://www.pc-canada.com/item/GV%2DRX580GAMING%2D4GD.html
  - https://www.pc-canada.com/item/DUAL%2DRX580%2DO8G.html
  - https://www.pc-canada.com/item/11265%2D05%2D20G.html
  - https://www.bhphotovideo.com/c/product/1559781-REG/gigabyte_gv_rx580gaming_8gd_rev2_0_radeon_rx_580_gaming_8g.html
...
